Repository Xovee/uestc-course, pull requests merged in 2019-05, with the labels that each got.

#10 修改主页的README.md
  README.md
Labels: enhancement

#12 Add materials of 软件架构模型与设计
  README.md
  仓库资源/模板/课程README模板.md
  课程目录/软件架构模型与设计/README.md
  课程目录/软件架构模型与设计/作业/README.md
  课程目录/软件架构模型与设计/作业/课程实验要求.txt
  课程目录/软件架构模型与设计/历年试题/2015年秋-期末考试-无答案.pdf
  课程目录/软件架构模型与设计/历年试题/2015年秋-期末考试-有答案.pdf
  课程目录/软件架构模型与设计/历年试题/README.md
  课程目录/软件架构模型与设计/复习资料/README.md
  课程目录/软件架构模型与设计/复习资料/blocks-优点.docx
  课程目录/软件架构模型与设计/复习资料/复习整理.docx
  课程目录/软件架构模型与设计/复习资料/实际项目-智能共享单车出行平台.docx
  课程目录/软件架构模型与设计/复习资料/课后习题.docx
  课程目录/软件架构模型与设计/复习资料/软件架构复习.docx
  课程目录/软件架构模型与设计/复习资料/软件架构复习总结-1.docx
  课程目录/软件架构模型与设计/复习资料/软件架构复习总结-2.docx
  课程目录/软件架构模型与设计/复习资料/软件架构模型与设计-总结.docx
  课程目录/软件架构模型与设计/复习资料/软件架构模型与设计-补充.docx
  课程目录/软件架构模型与设计/复习资料/软件架构模型与设计-附加整理.docx
  课程目录/软件架构模型与设计/教材/README.md
Labels: enhancement, resource contribution

#14 课程历年试题资源完善
  课程目录/网络安全理论与技术/历年试题/2016年秋-期末考试-无答案.pdf
  课程目录/网络安全理论与技术/历年试题/README.md
  课程目录/计算机网络/历年试题/2015年春-期中考试-无答案.docx
  课程目录/计算机网络/历年试题/2015年春-期中考试-有答案.doc
  课程目录/计算机网络/历年试题/README.md
  课程目录/软件架构模型与设计/历年试题/2015年秋-期末考试-无答案.pdf
  课程目录/软件架构模型与设计/历年试题/2015年秋-期末考试-有答案.pdf
  课程目录/随机过程与排队论/历年试题/2012年-期末考试-无答案.docx
  课程目录/随机过程与排队论/历年试题/2012年-期末考试-无答案.pdf
  课程目录/随机过程与排队论/历年试题/2014年秋-期末考试-无答案.pdf
  课程目录/随机过程与排队论/历年试题/2014年秋-期末考试-部分答案.pdf
  课程目录/随机过程与排队论/历年试题/2015年-期末考试-仅答案-2.docx
  课程目录/随机过程与排队论/历年试题/2015年-期末考试-仅答案.doc
  课程目录/随机过程与排队论/历年试题/2015年春-期末考试-无答案.docx
  课程目录/随机过程与排队论/历年试题/README.md
Labels: enhancement, resource contribution

#15 Course description
  仓库资源/模板/课程README模板.md
  仓库资源/模板/课程名.zip
  课程目录/神经网络与深度学习/README.md
  课程目录/组合优化理论/README.md
  课程目录/网络安全理论与技术/README.md
  课程目录/网络计算模式/README.md
  课程目录/随机过程与排队论/README.md
  课程目录/高级计算机结构/README.md
Labels: resource contribution
